### ISSUE TITLE
Does this only work with status code field?

### ISSUE THREAD

**Issue by ArtKarp** [VinnyDyn/StatusReasonKanban#11]
Can you choose a field other than status? Something else, like an option set field that has process steps that are different than status?  That would be really useful to me.

**Comment by VinnyBasile** [comment]
Hello @ArtKarp!

Unfortunately no, I considered this feature, but a I didn't evolve because the Microsoft launch the oficial Kanban.
I will retake this topic, please wait some days.

Thank your for your feedback!

**Comment by ArtKarp** [comment]
I looked at the official one, but it seems that it only uses the status field, unless I missed something.  So that really limits it usefulness too.

**Comment by VinnyBasile** [comment]
Hi @ArtKarp!
I'm finishing the development... wait more one or two days ;)

![image](https://user-images.githubusercontent.com/36446614/85204416-b3642e80-b2ea-11ea-8398-d9d36159fb28.png)

**Comment by ArtKarp** [comment]
Wow..the update looks really cool.  I will check it out this week.
-Thanks
