### ISSUE TITLE
Kanban solution throwing an "Resource not found for <entity>" error

### ISSUE THREAD

**Issue by Mcai282** [VinnyDyn/StatusReasonKanban#3]
Hi Vinny,

Love the PCFs. I tried importing the latest managed solution in your release and set the view for a custom activity entity I've created and it's throwing a ""Resource not found for <entity>"

![image](https://user-images.githubusercontent.com/54522237/66026201-a07eb380-e53b-11e9-9b06-0f39976db1b2.png)

Any idea what may be causing the issue?

**Comment by VinnyBasile** [comment]
Hi @Mcai282 , sorry for the delay...
Wich entity you associate to PCF?

**Comment by Mcai282** [comment]
> Hi @Mcai282 , sorry for the delay...
> Wich entity you associate to PCF?

Hi @VinnyDyn . Thank you for the reply! 

I created a custom activity entity and associated the PCF with that.

**Comment by VinnyBasile** [comment]
Hi @Mcai282, can you try install the [new version](https://github.com/VinnyDyn/StatusReasonKanban/releases/tag/1.1.3)?
