### ISSUE TITLE
not able to make it work

### ISSUE THREAD

**Issue by acehaddock** [VinnyDyn/StatusReasonKanban#5]
i have imported the Managed solution but every time i try to use the PCF nothing shows.  i have status code in the view as required.  can you provided a updated how to example in the read me?

**Comment by VinnyBasile** [comment]
Hi @acehaddock! Is StatusReasonKanban dosen't showing to add on Views, Subgrids and Entities?

<img src="https://github.com/VinnyDyn/StatusReasonKanban/blob/master/Images/control-details.png" width="200" height="200"/>
