### ISSUE TITLE
Error while using the control in test

### ISSUE THREAD

**Issue by ntarakaram1980** [VinnyDyn/StatusReasonKanban#6]
TS2345: Argument of type 'string' is not assignable to parameter of type 'ReadableStream<any>'.
[20:18:55] [start]  Failed:
[pcf-1033] [Error] An error occurred compiling or bundling the control

Can you please advice?

**Comment by VinnyBasile** [comment]
Hello @ntarakaram1980!
Did you try this approach?

### \node_modules\@types\xrm\index.d.ts\Xrm.ExecuteResponse
Change the attribute body from 'string' to 'ReadableStream':
```typescript
 interface ExecuteResponse {
        /**
         * (Optional). Object.Response body.
         */
        body: ReadableStream;
```
