### ISSUE TITLE
Option to change color of read-only status/status reason of system entities

### ISSUE THREAD

**Issue by khoait** [VinnyDyn/StatusReasonKanban#8]
Hi,

System entity like Task has read-only status reasons such as Completed and Canceled, so we can't change the color which is blue by default. It would be great if we have option to override this color.

Thanks.

**Comment by VinnyBasile** [comment]
Hello @khoait ! I don't know why the Microsoft don't allow we modify the hexadecimal value, but I found a workaround...

![image](https://user-images.githubusercontent.com/36446614/81871614-92235c00-954e-11ea-8c97-42e4ea5652fc.png)

1. Access the Status Code attribute using the old version.
2. Press F12.
3. Remove the property 'disabled' of select.
4. Change the Status and modify the colors.

![image](https://user-images.githubusercontent.com/36446614/81871918-27beeb80-954f-11ea-9aad-c155c5698948.png)
