### ISSUE TITLE
PCF NN Tags Does not Load on Create, Even after the first Save attempt.

### ISSUE THREAD

**Issue by PierreBouAoun** [VinnyDyn/StatusReasonKanban#9]
Hi there,

When opening a create form, the values in the PCF are not loaded.
After saving the record, we'll have to hit the Refresh button on the unified interface to make them appear.

Do you have a solution for this ?

**Comment by VinnyBasile** [comment]
Hi @PierreBouAoun !
About the "create form", the control won't show the values, this approach is equals to native sub-grids, where we can't relate records that dosen't exists yet.

I will check a solution to resolve the problem on save the record, thank you for the feedback!

**Comment by VinnyBasile** [comment]
@PierreBouAoun done!
You can download the solution here: https://github.com/VinnyDyn/StatusReasonKanban/releases/tag/1.7.4.1

**Comment by PierreBouAoun** [comment]
That's Great Thanks!
Minor request, can we have the same old publisher VinnyB instead of vinnyb in order to update it directly.
